# -*- fill-column: 80; -*-
version: "3"
services:
  unbound: # private service as backend of pihole
    container_name: dup-unbound
    hostname: dup-unbound
    build: vendor/docker-unbound/1.15.0/
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    # must be running
    restart: unless-stopped

  pihole: # public-facing
    container_name: dup-pihole
    hostname: dup-pihole
    image: docker.io/pihole/pihole:latest
    environment:
      PIHOLE_DNS_: dup-unbound # enforce the dns source used by pihole program
      DNSSEC: true
      WEBPASSWORD: pihole
    volumes:
      - ./pihole/etc:/etc/pihole/
      - ./pihole/masq:/etc/dnsmasq.d/
      - ./pihole/adlists:/etc/adlists/:ro
      - ./pihole/adcron/update-adlists:/etc/cron.d/adcron:ro
    # configure DNS servers to avoid issues from `pihole -g`.  ref:
    # https://github.com/pi-hole/docker-pi-hole/issues/342#issuecomment-430252832
    dns:
      - 127.0.0.1
      - 1.1.1.1
    extra_hosts:
      pi.hole: 127.0.0.1
    # ref: https://github.com/pi-hole/docker-pi-hole
    depends_on:
      - unbound
    cap_add:
      - NET_ADMIN
    # exported ports
    ports:
      - 5354:53/udp
      - 5354:53/tcp
      - 8880:80/tcp
    # must be running
    restart: unless-stopped
