version: "3"
services:
  unbound: # private service as backend of pihole
    container_name: dup-unbound
    hostname: dup-unbound
    build: vendor/docker-unbound/1.15.0/
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    # exposed ports
    # ports: []
    # must be running
    restart: unless-stopped

  pihole: # public-facing
    container_name: dup-pihole
    hostname: dup-pihole
    image: docker.io/pihole/pihole:latest
    environment:
      PIHOLE_DNS_: dup-unbound # enforce its dns entries
      DNSSEC: true
    volumes:
      - ./pihole/etc:/etc/pihole/
      - ./pihole/masq:/etc/dnsmasq.d/
    # ref: https://github.com/pi-hole/docker-pi-hole
    # dependencies
    depends_on:
      - unbound
    # add capability
    cap_add:
      - NET_ADMIN
    # exported ports
    ports:
      - 5354:53/udp
      - 5354:53/tcp
      - 8880:80/tcp
    # must be running
    restart: unless-stopped
